apiVersion: v1
kind: Service
metadata:
  name: springsample-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: springsample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

